config/routes.rb
Rails.application.routes.draw do

  get 'likes/create'
  get 'likes/destroy'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  root 'home#home'
  get '/support', to: 'home#support'

  devise_for :users, controllers: { registrations: 'users/registrations' }

  resource :account, :only => [:show, :edit] do
    resource :name, :only => [:edit, :update], module: "accounts"
    resource :email, :only => [:edit, :update], module: "accounts"
    resource :password, :only => [:edit, :update], module: "accounts"
    resource :image, :only => [:edit, :update], module: "accounts"
  end

  resources :items do
    resources :comments, only: [:create, :destroy, :edit, :update]
    resource :likes, only: [:create, :destroy]
  get :likes, on: :collection
  end

  resource :contacts, :only => [:new, :create]

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def home
    @item = Item.order(created_at: :desc).limit(8)
    @comment = Comment.order(created_at: :desc).limit(5)
  end

  def support
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/home.html.erb
<div class="home_about col-md-12">
  <p>ギタコミは皆様からの口コミをまとめた、ギターに特化した口コミ共有サービスです。<br>
  失敗したくない機材選びに役に立ちたい、様々なサイトに広がった口コミを一括にまとめたい、シンプルで見やすく使いやすい設計にしたい、そんな思いで作成しました。</p>
  <div class="text-center">
    <% if user_signed_in? %>
      <%= link_to "アイテムを探す", items_path, class:"btn btn-info btn-lg w-50" %>
    <% else %>
      <%= link_to "新規登録", new_user_registration_path, class: "btn btn-info w-25" %>
      <%= link_to "ログイン", new_user_session_path, class: "btn btn-info ml-2 w-25" %>
    <% end %>
  </div>
</div>

<div>
  <h3 class="home_title">　新着コメント</h3>
  <% @comment.each do |comment| %>
      <%= render 'shared/comments', comment: comment %>
  <% end %>

  <h3 class="home_title">　新着アイテム</h3>
  <div class="row">
    <% @item.each do |item| %>
      <%=render 'items/items', item: item %>
    <% end %>
  </div>
  <div class="text-center">
      <%= link_to "もっとアイテムを探す", items_path, class:"btn btn-success" %>
  </div>
</div>

app/views/home/support.html.erb
<h1>サポート</h1>