config/routes.rb
Rails.application.routes.draw do

  get 'likes/create'
  get 'likes/destroy'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  root 'home#home'
  get '/support', to: 'home#support'

  devise_for :users, controllers: { registrations: 'users/registrations' }

  resource :account, :only => [:show, :edit] do
    resource :name, :only => [:edit, :update], module: "accounts"
    resource :email, :only => [:edit, :update], module: "accounts"
    resource :password, :only => [:edit, :update], module: "accounts"
    resource :image, :only => [:edit, :update], module: "accounts"
  end

  resources :items do
    resources :comments, only: [:create, :destroy, :edit, :update]
    resource :likes, only: [:create, :destroy]
  get :likes, on: :collection
  end

  resource :contacts, :only => [:new, :create]

end

app/models/item.rb
class Item < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :users, through: :likes

  validates :name, presence: true
  validates :subject, presence: true, length: {maximum:400}

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :admin_user, only: [:edit, :new, :destroy, :create]
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def index
    @items = Item.all.order(created_at: :desc).page(params[:page])
    @q = Item.ransack(params[:q])
    @result = @q.result(distinct: true)
    @result = @result.order(created_at: :desc)
  end

  def show
    @comment = Comment.new
    @comments = @item.comments
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.create(item_params)
    if @item.save
      flash[:notice] = "新規アイテムを登録しました"
      redirect_to root_path
    else
      flash[:error] = "新規アイテム登録できませんでした"
      render 'new'
    end
  end

  def edit
  end

  def update
    if @item.update(item_params)
      flash[:notice] = "アイテムを更新しました"
      redirect_to @item
    else
      flash[:error] = "アイテム更新できませんでした"
      render 'edit'
    end
  end

  def destroy
    @item.destroy
    flash[:error] = "アイテムを削除しました"
    redirect_to items_path
  end

private
  def item_params
    params.require(:item).permit(:name, :company, :image_url, :subject, :url)
  end

  def set_item
    @item = Item.find(params[:id])
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_with model: @item do |f|%>
  <div class="form-group">
    <%= f.label :neme, "アイテム名" %><br>
    <%= f.text_field :name, id: "item_name", :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :company, "メーカー" %><br>
    <%= f.text_field :company, id: "item_company", :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :url, "https://amazon.jp/dp/ASIN/" %><br>
    <%= f.text_field :url, id: "url", :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :subject, "説明" %><br>
    <%= f.text_area :subject, id: "item_subject", :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :image_url, "画像[https://images-na.ssl-images-amazon.com/images/P/[ASIN].09.LZZZZZZZ]" %><br>
    <%= f.text_area :image_url, id: "image_url", :class => "form-control" %>
  </div>

  <div>
    <%= f.submit "登録する" %>
  </div>
<% end %>

app/views/items/_items.html.erb
<div class="col-md-3 col-sm-4 col-xs-12">
  <div class="card mb-3">
      <%= link_to item_path(item) do%>
        <%= image_tag item.image_url, class: "p-2 card-img-top text-center" %>
      <% end %>
    <div class="card-body pt-1 border-top">
      <span class="card-title"><%= link_to item.name, item_path(item) %></span>
      <br><%= item.company %>
      <div id="star-rate-<%= item.id %>"></div>
        <%= render 'shared/star', result: item %>
      <p>口コミ：<%= item.comments.count %>件</p>
      <span class=" text-center"><%= render 'likes/like_button', item: item %></span>
    </div>
  </div>
</div>

app/views/items/edit.html.erb
<h2>アイテム編集</h2>
<%= render 'items/form'%>

app/views/items/index.html.erb
<% breadcrumb :items %>

<div class="mt-3">
  <h2 class="text-center my-4">アイテム一覧検索</h2>

  <div class="row">
    <div class="text-center mx-auto">
      <%= search_form_for @q, class: "form-inline" do |f| %>
        <div class="form-group">
          <%= f.search_field :name_or_company_cont, :placeholder => "キーワードで検索", class: "form-control input-lg mx-2 mt-2", size: 60 %>
          <%= f.submit "検索する", :class => "btn btn-success mt-2" %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="mt-4">
    <% if @result.any? %>
      <p>検索結果：<%= @result.count %>件</p>
      <div class="row">
        <% @result.each do |result| %>
          <%=render 'items/items', item: result %>
        <% end %>
      </div>
      <%= paginate @items %>
    <% else %>
      <P>検索結果：見つかりませんでした</p>
    <% end %>
  </div>
</div>

app/views/items/new.html.erb
<h2>アイテム登録</h2>
<%= render 'items/form'%>

app/views/items/show.html.erb
<% breadcrumb :item, @item %>
<h1 class="text-center"><%= @item.company %> / <%= @item.name %></h1>

<div class="row item_content">
  <div class="col-md-12 text-center mb-3">
    <%= image_tag @item.image_url, width: '' %>
  </div>

  <div class="col-md-6">
    <span id="star-rate-<%= @item.id %>"></span>
    <span>（口コミ：<%= @item.comments.count %>件）</span>
    <%= render 'shared/star', result: @item %>
    <p><%= @item.subject %></p>
    <%= render 'likes/like_button', item: @item %>
  </div>

  <div class="col-md-6">
    <p><%= link_to "amazonで見る", @item.url, target: :_blank %><br>
    <%= link_to "楽天で見る", "https://search.rakuten.co.jp/search/mall/#{@item.name}/", target: :_blank %><br>
    <%= link_to "サウンドハウスで見る", "https://www.soundhouse.co.jp/search/index?x=0&y=0&search_all=#{@item.name}&s_large_category_cd=&s_mid_category_cd=&i_type=a", target: :_blank %></p>
  </div>

  <% if user_signed_in? %>
    <% if current_user.admin? %>
      <div class="col-md-12 text-right">
        <p><%= link_to "編集", edit_item_path, class:"btn btn-success btn-sm" %>
        <%= link_to "削除", item_path, method: :delete, data: { confirm: "本当に削除しますか?" }, class:"btn btn-success btn-sm" %></p>
      </div>
    <% end %>
  <% end %>
</div>

<h4 class="text-center"><%= @comments.count %> 件の口コミ</h4>
  <div>
    <% @comments.each do |comment| %>
      <%= render 'shared/comments', comment: comment %>
    <% end %>
  </div>

  <h4 class="text-center">口コミを投稿する</h4>
  <div class="col-md-12 font-weight-bold mt-2">
      <% if user_signed_in? %>
        <%= render 'comments/comments_form' %>
      <% else %>
        <p>口コミを投稿するには<%= link_to "ログイン", new_user_session_path %>してください</p>
      <% end %>
    </div>
</div>