config/routes.rb
Rails.application.routes.draw do

  get 'likes/create'
  get 'likes/destroy'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  root 'home#home'
  get '/support', to: 'home#support'

  devise_for :users, controllers: { registrations: 'users/registrations' }

  resource :account, :only => [:show, :edit] do
    resource :name, :only => [:edit, :update], module: "accounts"
    resource :email, :only => [:edit, :update], module: "accounts"
    resource :password, :only => [:edit, :update], module: "accounts"
    resource :image, :only => [:edit, :update], module: "accounts"
  end

  resources :items do
    resources :comments, only: [:create, :destroy, :edit, :update]
    resource :likes, only: [:create, :destroy]
  get :likes, on: :collection
  end

  resource :contacts, :only => [:new, :create]

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:

    if user && user.admin?
      can :access, :rails_admin
      can :manage, :all
    end
    
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def liked?(user)
    likes.where(user_id: user.id).exists?
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :item

  validates :content, presence: true, length: {maximum:300}
  validates :title, presence: true, length: {maximum:50}
  validates :rate, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1
  }, presence: true
end

app/models/contact.rb
class Contact < ApplicationRecord
  before_save { email.downcase! }
  validates :name, presence: true, length: {maximum:50}
  validates :email, presence: true, length: {maximum:255},
                    format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i}
  validates :message, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :users, through: :likes

  validates :name, presence: true
  validates :subject, presence: true, length: {maximum:400}

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :item
  validates :user_id, uniqueness: { scope: :item_id }
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :image, ImageUploader

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :comments, dependent: :destroy
  has_many :items, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_items, through: :likes, source: :item

  validates :name, presence: true, length: { maximum: 30 }

  def remember_me
    true
  end

  def like(item)
    likes.find_or_create_by(item_id: item.id)
  end

  def unlike(item)
    like = likes.find_by(item_id: item.id)
    like.destroy if like
  end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :authenticate_user!

  def show
    @comments = Comment.all.order(created_at: :desc).page(params[:page])
    @items = current_user.like_items.page(params[:page]).per(4)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_item, only: [:create, :edit, :update]

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      flash[:notice] = "口コミを編集しました"
      redirect_to @item
    else
      flash[:error] = "口コミを編集できませんでした"
      redirect_back(fallback_location: root_path)
    end
  end

  def create
    @comment = @item.comments.create(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      flash[:notice] = "口コミを投稿しました"
      redirect_back(fallback_location: root_path)
    else
      flash[:error] = "口コミを投稿できませんでした"
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    Comment.find(params[:id]).destroy
    flash[:error] = "口コミを削除しました"
    redirect_back(fallback_location: root_path)
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :title, :rate)
  end

  def set_item
    @item = Item.find(params[:item_id])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def home
    @item = Item.order(created_at: :desc).limit(8)
    @comment = Comment.order(created_at: :desc).limit(5)
  end

  def support
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :admin_user, only: [:edit, :new, :destroy, :create]
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def index
    @items = Item.all.order(created_at: :desc).page(params[:page])
    @q = Item.ransack(params[:q])
    @result = @q.result(distinct: true)
    @result = @result.order(created_at: :desc)
  end

  def show
    @comment = Comment.new
    @comments = @item.comments
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.create(item_params)
    if @item.save
      flash[:notice] = "新規アイテムを登録しました"
      redirect_to root_path
    else
      flash[:error] = "新規アイテム登録できませんでした"
      render 'new'
    end
  end

  def edit
  end

  def update
    if @item.update(item_params)
      flash[:notice] = "アイテムを更新しました"
      redirect_to @item
    else
      flash[:error] = "アイテム更新できませんでした"
      render 'edit'
    end
  end

  def destroy
    @item.destroy
    flash[:error] = "アイテムを削除しました"
    redirect_to items_path
  end

private
  def item_params
    params.require(:item).permit(:name, :company, :image_url, :subject, :url)
  end

  def set_item
    @item = Item.find(params[:id])
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    @like = current_user.likes.create(item_id: params[:item_id])
    @like.save
    flash[:notice] = "#{@like.item.name}をお気に入り登録しました。"
    redirect_back(fallback_location: root_path)
  end

  def destroy
    current_user.likes.find_by(item_id: params[:item_id]).destroy
    flash[:error] = "お気に入り登録を解除しました。"
    redirect_back(fallback_location: root_path)
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def bootstrap_alert(key)
    case key
    when "alert"
      "warning"
    when "notice"
      "success"
    when "error"
      "danger"
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/layouts/_flash_message.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= bootstrap_alert(key) %>">
    <strong>
      <%= value %>
    </strong>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer pt-4 font-small mt-5">
  <div class="container">
    <div class="row">
      <div class="col-md-6 mt-md-0 mt-3">
        <span  class="footer-logo pb-0">
          <%= link_to root_path do %>
            <%= image_tag 'logo.png', alt: "ギタコミ", height: '50px' %>
          <% end %>
        </span>
      </div>
      <div class="col-md-6 mt-md-0 mt-3">
        <ul>
          <li><%= link_to "お問い合わせ", new_contacts_path %></li>
          <li><%= link_to "サポート", support_path %></li>
          <li>利用規約</li>
          <% if user_signed_in? %>
            <% if current_user.admin? %>
              <li><%= link_to "管理者ページ", rails_admin_path %></li>
              <li><%= link_to "アイテム登録", new_item_path %></li>
            <% end %>
          <% end %>
        </ul>
      </div> 
    </div>
  </div>
    <div class="col-md-12 text-center copylight">
      <small>© 2020. All Rights Reserved.</small>
    </div>
</footer>

app/views/layouts/_header.html.erb
<header class="sticky-top">
  <nav class="navbar navbar-expand-sm navbar-light bg-light mb-3">
    <div class="container">
      <h1>
        <%= link_to root_path do %>
          <%= image_tag 'logo.png', alt: "ギタコミ", height: '50px' %>
        <% end %></h1>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
        <ul class="nav navbar-nav">
          <li class="nav-item">
            <%= link_to "アイテム一覧検索", items_path %>
          </li>
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "マイページ", account_path(current_user) %>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, data: { confirm: "本当にログアウトしますか?" } %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "新規登録", new_user_registration_path %>
            </li>
            <li class="nav-item">
              <%= link_to "ログイン", new_user_session_path %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GuitarApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'star' %>
  </head>

  <body>
  <%= render 'layouts/header' %>
  <div class="container">
    <%= breadcrumbs separator: " &rsaquo; "%>
    <%= render 'layouts/flash_message' %>
    <div class="mt-4">
      <%= yield %>
    </div>
  </div>
  <%= render 'layouts/footer' %>
  </body>
</html>

app/views/shared/_comments.html.erb
<div class="home_comment mb-3">
  <div class="row">
    <div class="col-md-2 col-3 text-center pt-2">
        <%= image_tag comment.user.image.url, width: '80px' %>
        <p><%= comment.user.name %></p>
    </div>

    <div class="col-md-6 col-9">
      <div class="comment_content">
        <span class="font-weight-bold"><%= comment.title %></span>
        <br><span id="star-rate-<%= comment.id %>"></span>

        <script>
          $('#star-rate-<%= comment.id %>').raty({
            size: 36,
            starOff:  '<%= asset_path('star-off.png') %>',
            starOn : '<%= asset_path('star-on.png') %>',
            starHalf: '<%= asset_path('star-half.png') %>',
            readOnly: true,
            score: <%= comment.rate %>,
          });
        </script>

      </div>
      <p class="pt-1"><%= comment.content %></p>
    </div>

    <div class="col-md-4 col-12 text-center">
      <%= link_to item_path(comment.item) do %>
        <%= image_tag comment.item.image_url, width: '220px' %>
      <% end %>
        <div>
          <p><%= link_to comment.item.name, item_path(comment.item) %> / <%= comment.item.company %></p>
        </div>
    </div>

      <div class="col-md-12 text-right">
        <p>
          <%= l comment.created_at %> に投稿
          <% if comment.user == current_user %>
            <%= link_to "口コミを削除する", item_comment_path(comment.item_id, comment.id), method: :delete, data: { confirm: "本当に削除しますか?" }, class:"btn btn-success btn-sm" %>
            <%= link_to "口コミを編集する", edit_item_comment_path(comment.item_id, comment.id), class:"btn btn-success btn-sm" %>
          <% end %>
        </p>
      </div>
  </div>
</div>

app/views/shared/_star.html.erb
<%= javascript_pack_tag 'star' %>

<!-- 星評価平均 -->
  <script>
    $('#star-rate-<%= result.id %>').raty({
      size: 36,
      starOff:  '<%= asset_path('star-off.png') %>',
      starOn : '<%= asset_path('star-on.png') %>',
      starHalf: '<%= asset_path('star-half.png') %>',
      readOnly: true,
      half: true,
      score: <%= result.comments.average(:rate).to_f.round(1) %>,
    });
  </script> 