config/routes.rb
Rails.application.routes.draw do

  get 'likes/create'
  get 'likes/destroy'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  root 'home#home'
  get '/support', to: 'home#support'

  devise_for :users, controllers: { registrations: 'users/registrations' }

  resource :account, :only => [:show, :edit] do
    resource :name, :only => [:edit, :update], module: "accounts"
    resource :email, :only => [:edit, :update], module: "accounts"
    resource :password, :only => [:edit, :update], module: "accounts"
    resource :image, :only => [:edit, :update], module: "accounts"
  end

  resources :items do
    resources :comments, only: [:create, :destroy, :edit, :update]
    resource :likes, only: [:create, :destroy]
  get :likes, on: :collection
  end

  resource :contacts, :only => [:new, :create]

end

app/controllers/accounts/emails_controller.rb
class Accounts::EmailsController < ApplicationController
  before_action :authenticate_user!
 
    def edit
    end
 
    def update
      if current_user.update_with_password(email_params)
        flash[:notice] = "メールアドレスを変更しました"
        redirect_to account_path
      else
        flash[:error] = "もう一度やりなおしてください"
        render :edit
      end
    end
 
    private

    def email_params
        params.require(:user).permit(:email, :current_password)
    end
end

app/controllers/accounts/images_controller.rb
class Accounts::ImagesController < ApplicationController
  before_action :authenticate_user!

  def edit
  end

  def update
    @user = current_user
    if @user.update(image_params)
      flash[:notice] = "画像を変更しました"
      redirect_to account_path
    else
      flash[:error] = "もう一度やりなおしてください"
      render :edit
    end
  end

  private

  def image_params
      params.permit(:image, :image_cache, :remove_image)
  end
end

app/controllers/accounts/names_controller.rb
class Accounts::NamesController < ApplicationController
  before_action :authenticate_user!

  def edit
  end

  def update
    @user = current_user
    if @user.update(name_params)
      flash[:notice] = "名前を変更しました"
      redirect_to account_path
    else
      flash[:error] = "もう一度やりなおしてください"
      render :edit
    end
  end

  private

  def name_params
    params.permit(:name)
  end

end

app/controllers/accounts/passwords_controller.rb
class Accounts::PasswordsController < ApplicationController
  before_action :authenticate_user!
 
    def edit
    end
 
    def update
      if current_user.update_with_password(password_params)
        sign_in(current_user, bypass: true)
        flash[:notice] = "パスワードを変更しました"
        redirect_to account_path
      else
        flash[:error] = "もう一度やりなおしてください"
        render :edit
      end
    end
 
    private

    def password_params
        params.require(:user).permit(:password, :password_confirmation, :current_password)
    end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :authenticate_user!

  def show
    @comments = Comment.all.order(created_at: :desc).page(params[:page])
    @items = current_user.like_items.page(params[:page]).per(4)
  end

end

app/helpers/accounts/emails_helper.rb
module Accounts::EmailsHelper
end

app/helpers/accounts/images_helper.rb
module Accounts::ImagesHelper
end

app/helpers/accounts/names_helper.rb
module Accounts::NamesHelper
end

app/helpers/accounts/passwords_helper.rb
module Accounts::PasswordsHelper
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/edit.html.erb
<% breadcrumb :account_edit %>

<h1 class="text-center">プロフィール編集</h1>
<%= image_tag current_user.image.url, :size => '200x200' %><br>
<%= link_to "プロフィール画像変更", edit_account_image_path(current_user) %>
<p>名前：<%= current_user.name %><br>
<%= link_to "変更", edit_account_name_path(current_user) %></p>
<p>メールアドレス：<%= current_user.email %><br>
<%= link_to "変更", edit_account_email_path(current_user) %></p>
<p><%= link_to "パスワード変更", edit_account_password_path(current_user) %></p>

<!-- <p><%= link_to "退会", user_registration_path, method: :delete, data: { confirm: "本当に退会しますか?" } %></p> -->

app/views/accounts/show.html.erb
<% breadcrumb :account %>

<h1 class="text-center"><%= current_user.name %>様のマイページ</h1>
<div class="text-center user_profile">
  <%= image_tag current_user.image.url, :size => '200x200' %><br>
  <p><%= link_to "プロフィール設定", edit_account_path, class:"btn btn-success mt-2" %></p>
</div>

<div>
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <a href="#tab1" class="nav-link active" data-toggle="tab">口コミ：<%= current_user.comments.count %>件</a>
    </li>

    <li class="nav-item">
      <a href="#tab2" class="nav-link" data-toggle="tab">お気に入り：<%= current_user.likes.count %></a>  
    </li>
  </ul>
</div>

<div class="tab-content pt-3">
  <div id="tab1" class="tab-pane active">
    <% if current_user.comments.any? %>
      <% @comments.each do |comment| %>
        <%= render 'shared/comments', comment: comment %>
      <% end %>
    <% else %>
      <p>投稿した口コミはありません</p>
    <% end %>
  </div>

  <div id="tab2" class="tab-pane mx-2">
    <div class="row">
      <% @items.each do |item| %>
        <%=render 'items/items', item: item %>
      <% end %>
    </div>
  </div>
</div>